dashboard/urls.py
from dashboard.views import ReportRequestView, DashboardView
from django.urls import path

urlpatterns = [
    path('', DashboardView.as_view(), name="default-dashboard"),
    path('reporte/', ReportRequestView.as_view(), name='reporte-clientes'),
]

leasy_challenge/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import CustomLoginView, CustomLogoutView
from dashboard.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("dashboard/", include("dashboard.urls")), 
    #path("contratos/", include("contracts.urls")),
    path("ventas/", include("ventas.urls")),
    path("operaciones/", include("operaciones.urls")),
    path("cobranzas/", include("cobranzas.urls")),
    
]

ventas/urls.py
from django.urls import path
from .views import VentasDashboardView,  ClientCreateView, ClientUpdateView

urlpatterns = [
    path("", VentasDashboardView.as_view(), name="ventas-dashboard"),
    path('nuevo/', ClientCreateView.as_view(), name='crear-cliente'),
    path('<int:pk>/editar/', ClientUpdateView.as_view(), name='editar-cliente'),
]

contracts/models.py
from django.db import models

# Create your models here.
from clients.models import Client
from vehicles.models import Vehicle
from django.db.models import Q, UniqueConstraint

class Contract(models.Model):
    BILLING_CYCLES = [
        ("weekly", "Semanal"),
        ("biweekly", "Quincenal"),
        ("monthly", "Mensual"),
    ]

    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name= "contracts") 
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, related_name= "contracts")
    billing_cycle = models.CharField(max_length=10, choices=BILLING_CYCLES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        constraints = [
            UniqueConstraint(fields=['client'], condition=Q(active=True), name='unique_active_contract_per_client'),
            UniqueConstraint(fields=['vehicle'], condition=Q(active=True), name='unique_active_contract_per_vehicle'),
        ]
    def __str__(self):
        return f"{self.client} - {self.vehicle} ({self.billing_cycle})"

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms

COLUMN_CHOICES = [
    # Campos del modelo Client
    ('first_name', 'Nombre'),
    ('last_name', 'Apellido'),
    ('document_number', 'Documento'),

    # Campos del modelo Contract (relación: contract)
    ('contract__start_date', 'Inicio del Contrato'),
    ('contract__billing_cycle', 'Ciclo de Facturación'),
    ('contract__amount', 'Monto del Contrato'),

    # Campos del modelo Vehicle (relación: contract → vehicle)
    ('contract__vehicle__brand', 'Marca del Vehículo'),
    ('contract__vehicle__model', 'Modelo del Vehículo'),
    ('contract__vehicle__plate', 'Placa'),
    ('contract__vehicle__vin', 'VIN'),
]

class ReportForm(forms.Form):
    columns = forms.MultipleChoiceField(
        choices=COLUMN_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Selecciona las columnas para el reporte"
    )

dashboard/views.py
import csv
from django.views import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib import messages
from clients.models import Client
from vehicles.models import Vehicle
from contracts.models import Contract
from django.db.models import Q
from django.shortcuts import redirect
from dashboard.forms import ReportForm
from django_rq import enqueue
import tempfile
from openpyxl import Workbook
import os
from .tasks import generate_report_and_send_email
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta 
from django.utils.dateparse import parse_date
from django.db.models import Prefetch, Subquery, OuterRef, DateField, Q
from clients.models import Client
from dashboard.services.dashboard_service import DashboardService


class DashboardView(LoginRequiredMixin, View):
    template_name = "dashboard/home.html"

    def get(self, request):
        query = request.GET.get("q", "").strip()
        clients = DashboardService.get_filtered_clients(query)
        page_obj = Paginator(clients, 20).get_page(request.GET.get("page"))
        return render(request, self.template_name, {"page_obj": page_obj, "query": query})
                 
    def post(self, request):
        file = request.FILES.get("file")
        if not file:
            return render(request, self.template_name, {"error": "Debes subir un archivo."})
        
        # if file.size > 5 * 1024 * 1024:
        #     return render(request, self.template_name, {"error": "Archivo inválido o demasiado grande."})
        try: 
                nuevos, duplicados = DashboardService.process_file(file)
                messages.success(request, f"{nuevos} clientes cargados. {duplicados} ya existían.")
                return redirect("default-dashboard")

        except Exception as e:
            return render(request, self.template_name, {"error": str(e)})
        
        
class ReportRequestView(LoginRequiredMixin, View):
    template_name = "dashboard/report_form.html"

    def get(self, request):
        form = ReportForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = ReportForm(request.POST)
        if form.is_valid():
            selected_columns = form.cleaned_data['columns']
            enqueue(generate_report_and_send_email, request.user.email, selected_columns)
            messages.success(request, "Tu reporte está siendo generado. Recibirás un correo en breve.")
            return redirect("default-dashboard")
        return render(request, self.template_name, {"form": form})

dashboard/templates/dashboard/home.html
{% extends 'base.html' %}
{% load extras %}
{% block title %}Dashboard{% endblock %}
{% block content %}
{% include "partials/header.html" %}
<a href="{% url 'crear-contrato' %}" class="btn btn-success mb-3">+ Nuevo Contrato</a>
<a href="{% url 'reporte-clientes' %}" class="btn btn-outline-info mb-4">Generar Reporte</a>
<a href="{% url 'ventas-dashboard' %}" class="btn btn-outline-info mb-4">Ventas</a>
<a href="{% url 'operaciones-dashboard' %}" class="btn btn-outline-info mb-4">Operaciones</a>
<a href="{% url 'cobranzas-dashboard' %}" class="btn btn-outline-info mb-4">Cobranzas</a>
{% comment %} <h2>Bienvenido, {{ request.user.first_name }}</h2>
<a href="{% url 'logout' %}" class="btn btn-outline-danger mb-3">Cerrar sesión</a> {% endcomment %}

<h4>Subir archivo (.csv) o (.xlsx)</h4>
<form method="post" enctype="multipart/form-data">

  {% csrf_token %}
  <div class="mb-3">
    <input type="file" name="file" accept=".csv" class="form-control" required>
  </div>
  <button type="submit" class="btn btn-primary">Subir</button>
</form>

{% if error %}
  <div class="alert alert-danger mt-3">{{ error }}</div>
{% endif %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
  {% endfor %}
{% endif %}

<hr class="my-4">

<h4>Dashboard</h4>
{% include "partials/navbar.html" %}
<form method="get" class="mb-3">
  <div class="input-group">
    <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Buscar por nombre, apellido, documento o vehiculo">
    <button class="btn btn-outline-secondary" type="submit">Buscar</button>
  </div>
</form>

{% if page_obj %}
  <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Documento</th>
      <th>Vehículo</th>
      <th>Contrato</th>
      <th>Ciclo</th>
      <th>Monto</th>
      <th>Inicio</th>
      <th>Activo</th>
    </tr>
  </thead>
  <tbody>
    {% for client in page_obj %}
        {% with contract=client.all_contracts.0 %}
    <tr>
      <td>{{ client.first_name }}</td>
      <td>{{ client.last_name }}</td>
      <td>{{ client.document_number }}</td>

      {% if contract %}
       <td>{{ contract.vehicle.brand }} {{ contract.vehicle.model }} - {{ contract.vehicle.plate }}</td>
       <td>#{{ contract.id }}</td>
       <td>{{ contract.get_billing_cycle_display }}</td>
       <!-- <td>{{ contract.end_date|default:"—" }}</td> -->
       <td>${{ contract.amount }}</td>
       <td>{{ contract.start_date }}</td>
       
       <td>{{ contract.active|yesno:"Sí,No" }}</td>
      {% else %}
        <td colspan="7">Sin contrato</td>
      {% endif %}
    </tr>
    {% endwith %}
    {% empty %}
    <tr><td colspan="10">No hay clientes registrados.</td></tr>
    {% endfor %}
  </tbody>
</table>

{% include "partials/navbar.html" %}
  {% comment %} <nav>
    <ul class="pagination">
      {% if client_page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ client_page_obj.previous_page_number }}&q={{ query }}">Anterior</a></li>
      {% endif %}
      <li class="page-item disabled"><span class="page-link">Página {{ client_page_obj.number }}</span></li>
      {% if client_page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ client_page_obj.next_page_number }}&q={{ query }}">Siguiente</a></li>
      {% endif %}
    </ul>
  </nav> {% endcomment %}

{% endif %}

{% comment %} <hr class="my-4">

<h4>Vehículos registrados</h4>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Placa</th>
      <th>VIN</th>
    </tr>
  </thead>
  <tbody>
    {% for v in vehicle_page %}
      <tr>
        <td>{{ v.brand }}</td>
        <td>{{ v.model }}</td>
        <td>{{ v.plate }}</td>
        <td>{{ v.vin|default:"—" }}</td>
      </tr>
    {% empty %}
      <tr><td colspan="4">No se encontraron vehículos.</td></tr>
    {% endfor %}
  </tbody>
</table> {% endcomment %}

{% endblock %}

dashboard/templates/dashboard/report_form.html
{% extends "base.html" %}
{% block title %}Generar Reporte{% endblock %}
{% block content %}

<h2>Generar Reporte de Clientes</h2>

<form method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
    <div class="mb-3">
      {{ field.label_tag }}
      {{ field }}
      {{ field.errors }}
    </div>
  {% endfor %}
  <button class="btn btn-primary">Generar y Enviar</button>
  <a href="{% url 'default-dashboard' %}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}